prometheus:
  image: prometheus
  ports:
    - 9090:9090
  volumes:
    - /data/prometheus:/prometheus
  container_name: "prometheus"
  links:
    - pushgateway

pushgateway:
  image: prom/pushgateway
  ports:
    - 9091:9091
  container_name: pushgateway

grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  container_name: grafana
  volumes:
    - /data/grafana:/var/lib/grafana
  links:
    - prometheus
