global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus-test'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    scrape_interval: 5s
    target_groups:
      - targets: ['172.30.35.35:9091']
